services:
  jupyterai:
    image: jupyter/tensorflow-notebook
    container_name: jupyterai-agustin
    ports:
      - "9999:8888"
    volumes:
      - ./work:/home/jovyan/work
      - /mnt/data:/home/jovyan/data
    environment:
      - --allow-root
      - --ip=0.0.0.0
